### ISSUE TITLE
Support for hadolint.

### ISSUE THREAD

**Issue by niksite** [AtomLinter/linter-docker#26]
Please consider to add support for alternative docker linters, e.g. hadolint (http://hadolint.lukasmartinelli.ch/) which do much more checks than dockerlint.

**Comment by Arcanemagus** [comment]
If their output is compatible with the _exact_ format that `dockerlint` outputs you can simply point the Executable Path setting at that instead of `dockerlint`. If the output is different however then it would be best to start that as a new linter package dedicated to it.

Let me know if you start one and want it added to this organization 😉.

**Comment by lucasdf** [comment]
Hi @niksite 
We have recently released a plugin for Hadolint. You can check it [here](https://github.com/AtomLinter/linter-hadolint).
